### PR TITLE
Dynamic username/password for db connections

### PR DESCRIPTION
**Pull request by gcpinckert**
Applies the following changes:
- Removes user input password, instead generates a random UUID upon `edamame init`.
- Creates kustomize config file to generate custom Secret for DB connection authentication
- Secret values are stored and pulled from gitignored location
- Added a 10 second timeout to ensure db container has time to start before connections are made

TODO:
- [ ] refactor 10 second timeout to use event driven paradigm (i.e. wait for "container ready" event)
- [ ] create additional kustomize configuration to dynamically apply test-id to load test yaml files

### CODE REVIEW

**Comment by westrachel** [comment]
I got an "[01:59:54:492] ✖ Error creating cluster: Error: ENOENT: no such file or directory, open '/Users/rachwest/Desktop/edamame/manifests/properties/psql.env'" when running edamame init, but adding an empty properties subdirectory and re-running 'edamame init' fixed it. When I ran a test, the grafana dashboard couldn't query from the database because password authentication failed for the "edamame" user, but I think I need to teardown my cluster and remake and re-test to confirm that that's an actual issue and not an issue with my pre-existing cluster/pvc stuff. When I teardown and re-make to re-test I'll remove the properties subfolder that I just made and see if I run into that properties subfolder doesn't exist issue again, because I don't think we had that issue yesterday when writing the psql.env file for the first time.

**Comment by gcpinckert** [comment]
I think this might be an issue because I had already made the `properties` subfolder, and never deleted it, just the file. It's probably better to store the `env` stuff in the `manifests` folder or even the root dir. I'll go ahead and make the changes while your cluster resets.

**Comment by gcpinckert** [comment]
Linking issue #29 and #20 for posterity.

**Comment by westrachel** [comment]
data is showing up in grafana after tearing down/remaking the cluster! I think we're good to merge this after the change is made for removing writing the psql.env file to a nonexistent /properties subfolder

**Comment by gcpinckert** [comment]
I've been able to successfully create a cluster and run a test after making the change to store the `env` file directly in the `manifests` folder. This seemed easiest, since the `file.path` method automatically applies this relative path directly to filenames.

**Pull request merged**
