### PR TITLE
added functions to kubectl to check for port forward processes, start…

### LINKED ISSUE #28: Use port forwarding instead of External IPs
External IPs (Load balancers) will force us to use authentication for the **DB API** and **Grafana server**. Investigate if port forwarding is appropriate for our use case, and make the switch.

### PR DESCRIPTION
**Pull request by westrachel**
… port forwarding, and end port forwarding where necessary
- updated all the functions in dbApi to use port forwarding
- added edamame grafana command to allow for local access to grafana dashboard via port forwarding
- updated readme for edamame grafana command
- removed grafana and dp-api services from their respective manifest yaml files, because we no longer need their external ips
- updated manifest.js to check for maxVUs when parsing the test script
- added test8.js and tested that the updates to the regex in manifest.js were working

This is to address #28 and #72

Resolves #28 and #72

### CODE REVIEW

**Comment by lukeoguro** [comment]
@westrachel Still in the middle of testing this, but Control+C isn't killing the Grafana server for me. Is it for you?

**Comment by westrachel** [comment]
what do you mean by grafana server? the grafana pod should still run. When you ctrl + c at the end of edamame grafana it brings you back to the next prompt in the console

**Comment by lukeoguro** [comment]
Sorry I should've been clearer! Running `edamame grafana` should create a port-forward to `localhost:3000`, and then ctrl + c should terminate the port-forward; i.e., I should no longer be able to access Grafana at `localhost:3000`. However, I'm still able to access Grafana at port 3000, even after ctrl + c. 

Not sure if this is just on my end.

**Comment by westrachel** [comment]
I'm still waiting for another cluster to re-test again, but even if that doesn't always break the connection I think it should be okay, because of the logic of `kubectl.tempPortForward()`, which always checks to see if there is a port forward process before re-running `kubectl port-fortward...`. So, a user should be able to re-run `edamame grafana`

**Comment by lukeoguro** [comment]
Omg you know what I did, I had a local Grafana up and running! 😂 So I'm actually not entirely sure what happened, and I'm gonna have to test everything again. Does `edamame grafana` tell you it wasn't able to run a port-forward if there's another application occupying `3000`?

**Comment by lukeoguro** [comment]
Love it, LGTM!

Screen Shot 2023-03-17 at 20 42 26

**Pull request merged**
